Add testCase version to TERCC batches
eiffel-community/eiffel pull request #286
Opened 2021-10-28 07:19 UTC by t-persson

### Applicable Issues

fixes: #288 

### Description of the Change

The `data.testCase` object in [EiffelTestCaseTriggeredEvent](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelTestCaseTriggeredEvent.md) share the same parameters as the [TERCC](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelTestExecutionRecipeCollectionCreatedEvent.md) except for `version`.
This change adds that `version` string to the `data.batches.recipes.testCase` object in the TERCC.

### Alternate Designs

It's a bit weird that we have this information duplicated between two events, but I can see the appeal of having it and easier being able to match what's in the TERCC and what has actually been triggered so I think the duplication still serves a purpose.

### Benefits

ETOS uses TERCCs for knowing what to test and if ETOS also knows which versions of the tests to use, then that's a bit benefit when implementing features such as "replay" (where we can replay the entire ETOS run).

### Possible Drawbacks

Duplication between these events might be a problem when we forget to update.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2021-11-03 08:30 UTC, t-persson commented
> The 4.2.0 version should be added to the version history in the md file

I added it, but did not know what to do with "Introduced in". Asked a question on slack about that.

2021-11-03 12:25 UTC, e-backmark-ericsson commented
This was somehow discussed when releasing the Lyon edition in #277 
I'd say we should do as in this example for now, and state "No edition set": https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelActivityFinishedEvent.md#version-history

2021-11-04 13:46 UTC, m-linner-ericsson requested changes
Markdown trickyness

2021-11-04 13:46 UTC, m-linner-ericsson commented on eiffel-vocabulary/EiffelTestExecutionRecipeCollectionCreatedEvent.md
> +__Description:__ The unique version of the identified test case to be executed. Where this property is not used it is assumed that test cases are not version controlled.
Markdown is a bit tricky sometimes

```suggestion
__Type:__ String  
__Required:__ No  
__Description:__ The unique version of the identified test case to be executed. Where this property is not used it is assumed that test cases are not version controlled.
```

Notice the two blank spaces. They will insert a breakline but not a new paragraph see [preview commit](https://github.com/eiffel-community/eiffel/blob/bd163f8f54c62ca5c33b4c8f9e5bb571a7c5cc9a/eiffel-vocabulary/EiffelTestExecutionRecipeCollectionCreatedEvent.md#databatchesrecipestestcaseversion) for the issue

2021-11-05 14:12 UTC, e-backmark-ericsson approved these changes

2021-11-10 15:29 UTC, m-linner-ericsson approved these changes

2021-11-10 16:05 UTC, e-backmark-ericsson commented
I will merge this as it is written by one of the maintainers (Tobias) and approved by me (maintainer) and a second TC member (Mattias).

2021-11-10 16:06 UTC, merged