Change definition of "introduced_in" field in the history tables
eiffel-community/eiffel pull request #354
Opened 2023-06-24 22:10 UTC by magnusbaeck

### Applicable Issues
Fixes #326
Fixes #327

### Description of the Change
The `introduced_in` field in entries of the history tables has previously only had a well-defined and obvious meaning for event versions that were the latest version in a released edition. To make the files more consistent and easier to maintain we change the field to be the Git tag where the event version was first introduced, or null if the version hasn't been released yet. This also makes the field machine-readable, and we'll render it to a clickable link in the Markdown to the documentation generator.

### Alternate Designs
None.

### Benefits
Easier to understand and maintain the documentation.

### Possible Drawbacks
In some cases the version history tables referenced commit SHA-1s. This change replaces this with edition references which is less granular. Of course, if you want to know exactly which commit introduced the version that is easily available from the git.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I    have the right to submit it under the open source license    indicated in the file; or

(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or

(c) The contribution was provided directly to me by some other    person who certified (a), (b) or (c) and I have not modified    it.

(d) I understand and agree that this project and the contribution    are public and that a record of the contribution (including all    personal information I submit with it, including my sign-off) is    maintained indefinitely and may be redistributed consistent with    this project or the open source license(s) involved.

Signed-off-by: Magnus Bäck \<magnus.back@axis.com>

2023-06-26 10:10 UTC, t-persson submitted a review, later dismissed

2023-06-28 07:19 UTC, m-linner-ericsson requested changes
Two things:
- **Change needed**: Noticed that the copyright headers needs update on all the files if we change them.
- **Comment**: If one tries to regenerate the Markdown files in an older edition using the YAML files, the result will differ from previous generated markdown (e.g. if you look at a older version via a tag)

2023-06-28 11:27 UTC, magnusbaeck commented
> If one tries to regenerate the Markdown files in an older edition using the YAML files, the result will differ from previous generated markdown (e.g. if you look at a older version via a tag)

Sure. That'll happen every time the documentation generator changes. That's fine since we keep all versions in separate files and therefore are able to generate documentation for any event.

2023-06-29 11:25 UTC, e-backmark-ericsson approved these changes

2023-06-29 11:26 UTC, m-linner-ericsson approved these changes

2023-06-29 12:04 UTC, merged